services:
  wordpress:
    build: ./wordpress
    ports:
      - 8000:80
    volumes:
      - ./wordpress/data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    links:
      - db:db

  db:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    build: ./phpmyadmin
    ports:
      - "8082:80"
    links:
      - db:db
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root    